server:
  port: 8080

spring:
  application:
    name: grid-trading

  datasource:
    url: jdbc:h2:mem:grid_trading
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# 安装 MySQL 后使用以下配置
#  datasource:
#    url: jdbc:mysql://localhost:3306/grid_trading
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.panda.gridtrading: INFO

baidu:
  ocr:
    app-id: 44973625
    api-key: 1ixcXpfDZIEwXgup6GuYz6uP
    secret-key: Uu6E8mHt9yscUKYfLE7zBqD7l3N96Aa7

ocr:
  match:
    tolerance-percent: 0.005
    time-window-seconds: 30
